name: promociones
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.1.5+10

environment:
  sdk: ">=2.1.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: 1.10.0
  firebase_auth: 2.0.0
  google_sign_in: ^4.0.1+3
  firebase_database: 7.1.0
  firebase_messaging: 10.0.0
  http: 0.13.3
  carousel_slider: ^1.3.0
  google_maps_flutter: ^0.5.21+7
  flutter_secure_storage: ^3.2.1+1
  intl: 0.17.0
  cached_network_image: 3.1.0
  fluttertoast: ^3.1.0
  location: ^2.3.5
  qr_flutter: ^2.0.0+51
  flutter_local_notifications: 9.8.0+1
  flutter_spinkit: ^3.1.0
  font_awesome_flutter: ^8.5.0
  firebase_crashlytics: 2.0.0
  firebase_analytics: 9.0.0
  dio: 4.0.6
  url_launcher: ^6.1.5




dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/markers/person.png
    - assets/offers.png
    - assets/firebase_logo.png
    - assets/markers/store-1.png
    - assets/markers/android/bigstore.png
    - assets/markers/android/headerstore.png
    - assets/markers/android/minimarket.png
    - assets/markers/android/neighborhoodstore.png
    - assets/markers/ios/bigstore.png
    - assets/markers/ios/headerstore.png
    - assets/markers/ios/minimarket.png
    - assets/markers/ios/neighborhoodstore.png
    - assets/markers/car.png
    - assets/markers/person2.png
    - assets/markers/android/person.png
    - assets/markers/ios/person.png
    - assets/markers/android/car.png
    - assets/customer.png
    - assets/logo.png
    - assets/empty.jpg
    - assets/cuponix.png
    
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
